//AUTH CONSTANTS
export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

//POSTS CONSTANTS
export const GET_POSTS = "GET_POSTS";
export const GET_POSTS_ERROR = "GET_POSTS_ERROR";
export const POST_COMMENT = "POST_COMMENT";

//ERROR CONSTANTS
export const CLEAR_ERRORS = "CLEAR_ERRORS";
